version: "3"

services:
  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: node-api
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - database

  database:
    image: mongo
    container_name: mongo-db

    ports:
      - "27017:27017"
