version: "3"

services:
  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-networks

  backend:
    build: ./backend
    container_name: node-api
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - database
    networks:
      - mern-networks

  database:
    image: mongo
    container_name: mongo-db
    environment:
      MONGO_INITDB_DATABASE: MERN
    ports:
      - "27017:27017"
    networks:
      - mern-networks
    volumes:
      - mongo-data:/data/db

networks:
  mern-networks:
    driver: bridge

volumes:
  mongo-data:
    driver: local
